### ISSUE TITLE
Provide a default init binary

### ISSUE THREAD

**Issue by yulianedyalkova** [cloudfoundry/bpm-release#121]
Hello! Have you ever thought of providing a default init binary that can be consumed by bpm users?

We (garden) noticed the following behaviour: initially we were providing the start script as an executable to the garden bpm process. That resulted in garden running as pid 1 in the namespace of the bpm container, but since garden spawns new processes and is not a reaper, we ended up having zombies.

Then we decided to wrap the garden_ctl in a `/bin/sh -c` but that led to garden always being forcefully killed on stop since `/bin/sh` does not propagate SIGTERM to its children. 

Our current solution is to use a small binary (https://github.com/krallin/tini which is also being used by `docker --init`) which does all of the magic and we are happy with it, but it made us think if maybe other bpm consumers would also profit from having this option in bpm and not having to take care of it themselves (as if providing the binary in the release, compiling it etc.)?

**Comment by xoebus** [comment]
Thanks for opening an issue. I like this idea!

I've started on a spike for this here: https://github.com/cloudfoundry/bpm-release/tree/init
