### ISSUE TITLE
Different digest for bpm-release?v=1.0.4

### ISSUE THREAD

**Issue by msahihi** [cloudfoundry/bpm-release#139]
I have a bmp version 1.0.4 with `41df19697d6a69d2552bc2c132928157fa91abe0` digest in my manifest and I noticed a change of digest to `c2cceb2d1e271a2f7c5e7c563a7b26f919ebc17a ` https://bosh.io/releases/github.com/cloudfoundry/bpm-release?all=1#v1.0.4.

at the same time, I downloaded the same version locally two times and I've got different digest
```
-rw-r--r--    1 msahihi  msahihi   128M May 21  2019 bpm-release?v=1.0.4
-rw-r--r--    1 msahihi  msahihi   128M Apr  2  2019 bpm-release?v=1.0.4-second

~ openssl sha1 bpm-release\?v=1.0.4
SHA1(bpm-release?v=1.0.4)= c2cceb2d1e271a2f7c5e7c563a7b26f919ebc17a
~ openssl sha1 bpm-release\?v=1.0.4-second
SHA1(bpm-release?v=1.0.4-second)= 41df19697d6a69d2552bc2c132928157fa91abe0
```
seems that **bpm-release?v=1.0.4** is created on May 21 and **bpm-release?v=1.0.4-second** on April 2 are different. Is it possible that you have different version in CDN ?

**Comment by xoebus** [comment]
bosh.io is out of our control and rebuilds all releases from source behind the scenes. I'm not sure why the SHAs would have changed though. You could use something like [diffoscope](https://diffoscope.org/) to see what the differences are between the two releases.

**Comment by xoebus** [comment]
Just took a look at the bosh.io build logs and it looks like due to some infrastructure recreation that bpm 1.0.4 was accidentally built twice in that time frame.

**Comment by xoebus** [comment]
Root cause seems to be that we moved the repository from the _cloudfoundry-incubator_ to _cloudfoundry_ organizations.

**Comment by msahihi** [comment]
@xoebus thanks for the clarification.
Will you removed the one with  `41df19697d6a69d2552bc2c132928157fa91abe0' digest ?

**Comment by xoebus** [comment]
The *cloudfoundry-incubator* repository doesn't exist anymore and so the de-facto one is probably the second one (41df19697d6a69d2552bc2c132928157fa91abe0).

As an aside, that version is pretty old and you should consider upgrading.

**Comment by radoslav-tomov** [comment]
The link  https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=1.0.4 redirects to a CDN -> AWS CloudFront. My only explanation is, that the migration caused inconsistencies and maybe there are CloudFront edge locations, which still have the old version with the wrong checksum (c2cceb2d1e271a2f7c5e7c563a7b26f919ebc17a).

I was never able to reproduce it, although we got an incident from a Bosh setup, which hit on it. The next run was fine. My guess is, that the CDN cache was invalidated and we are good to go.
