### ISSUE TITLE
Share the host's process namespace with the Bosh BPM container

### ISSUE THREAD

**Issue by istvanballok** [cloudfoundry/bpm-release#142]
When trying to create a Bosh release with BPM for telegraf, to collect the metrics of the bosh managed jobs on a VM, we noticed that the procstat input plugin does not work probably because the BPM container is hard coded to use a separate process namespace.

Falling back to the pure monit based approach does not feel right, so I report this github issue.

BPM configuration documentation: https://bosh.io/docs/bpm/config/
Slack discussion: https://cloudfoundry.slack.com/archives/C7A0K6NMU/p1589886990004800?thread_ts=1585645037.002900&cid=C7A0K6NMU

Idea: make it configurable like with docker: https://docs.docker.com/engine/reference/run/#pid-settings---pid

**Comment by rkoster** [comment]
Fixed in https://github.com/cloudfoundry/bpm-release/pull/144
