### ISSUE TITLE
Add version numbers to blob names

### ISSUE THREAD

**Issue by kdykeman** [cloudfoundry/bpm-release#28]
Because blobs can be named anything which makes it hard to track it's origins (src and version), most folks have adopted a pattern that would suggest naming the two blobs something more like:
1. golang/go1.9.2-linux-amd64.tar.gz
1. runc/runc-1.0.0-rc4-linux-amd64

**Comment by xoebus** [comment]
Sounds like a good idea but we'll need to work out how to make this work with our auto-updating dependencies.
