### ISSUE TITLE
Mount propagation support for docker volume plugins running as BPM jobs

### ISSUE THREAD

**Issue by julian-hj** [cloudfoundry/bpm-release#73]
As a prerequisite for migrating volume services to BPM, we would need for BPM to optionally support mount propagation.  Mount propagation is necessary because volume plugins mounting stuff into a container need for the resulting mount to be visible out in the diego cell OS so that it can get picked up by the executor and handed off to Garden.

To do this, BPM would need to be able to:
1) create a shared mount path that can be bound into the BPM container [like so](https://github.com/cloudfoundry/csi-plugins-release/blob/master/jobs/csi-nfs-plugin/templates/ctl.erb#L30)
2) launch the BPM container with `process.linux.rootfsPropagation` set to `shared` [like so](https://github.com/cloudfoundry/csi-plugins-release/blob/master/jobs/csi-nfs-plugin/templates/config.json.erb#L166)

Note that this is probably not the only thing we'd need to figure out.  Some other stuff we do is:
1) install kernel modules in pre-start scripts.  Modules like fuse and nfs-common are missing from the stemcell, so we have to install them in our pre-start scripts.  Not clear if we can do this from a container?
2) fuse modules require access to /dev/fuse.  This can be bind mounted in, which is no biggie, but I suspect that it's not there for BPM?

**Comment by xoebus** [comment]
mount("none", "/home/cb/workspace/bpm-release/scratch/two", NULL, MS_SHARED, NULL)

**Comment by julian-hj** [comment]
This is the original moby PR where that rootfsPropagation option was added.  The discussion has better documentation than I've seen elsewhere.
https://github.com/moby/moby/pull/15648

It does seem like all 3 options might be good to support.  Some containers might just be consumers of new mounts, in which case they'd just need "slave" whereas others (like volume drivers) will be producers of new mounts in which case we need "shared".

**Comment by xoebus** [comment]
Some of this work has now been done on master (shared mounts but not rootfsPropagation). Does that help unblock any of these use cases or do you need both in order for this to work?

**Comment by julian-hj** [comment]
IIRC, rootFsPropagation is necessary to get volume mounts out of the bpm container, so I suspect that the current state is kind of like that shiny new bike path they added on the east span of the bay bridge; it would get our volume mount only as far as yerba buena island, but not all the way to work.

**Comment by xoebus** [comment]
This doesn't match up with some experimenting I just did. From what I could see as long as you create the new mounts inside a shared volume then they will appear in all jobs which have the shared volume.

**Comment by julian-hj** [comment]
That's entirely possible--it's been nearly a year since I last looked at this so it's quite possible that I am misremembering or that the landscape has shifted or both of those things.

So, you are able to mount a volume inside a shared mount in one BPM container, and see it showing up in another BPM container?  If so, then that's more or less the requirement, and you can close this issue.

**Comment by xoebus** [comment]
Yep, that seems to work. I'm happy to leave this open until we can confirm
that you're unblocked.

There's still the issue of devices being mounted as `nodev` which may block
some of your drivers. I'm hoping to remedy that in the next release.

**Comment by julian-hj** [comment]
I believe that we only need /dev/fuse but I could be mistaken.  I will take the blocker off of our BPM story and we will hopefully find some time to try this again sometime soon.

**Comment by julian-hj** [comment]
Ah, right.  NFS is still blocked on #98 but we might be able to give the smbdriver a try.  That one doesn't use FUSE.

**Comment by julian-hj** [comment]
I agree with bosh-admin-bot that this can be closed.
