### ISSUE TITLE
`dev` mounts for volume plugins running as BPM jobs

### ISSUE THREAD

**Issue by julian-hj** [cloudfoundry/bpm-release#98]
[This code line](https://www.pivotaltracker.com/n/projects/1518687/stories/160187993/comments/193922477) hard codes BPM mounts to be `nodev` but in order for fuse mounting to work in a BPM process, we need to be able to mount `\dev\fuse` as a device.

So, I think we need for that to be an option on `unsafe.unrestricted_volume` mounts, just like `exec`/`noexec` is.

Could we have an `allow_device` flag in that context maybe?

Related persi team spike story here: https://www.pivotaltracker.com/story/show/160187993

**Comment by xoebus** [comment]
I'd like to avoid adding more flags where possible. You've already expressed intent that you want to use FUSE with the volume without requiring people know the correct flag incantation too. It's interesting that `/dev/log` didn't need this flag to be usable. Are there a set of devices which don't work with the `nodev` mount option and we can just do the right thing?

**Comment by xoebus** [comment]
I guess `/dev/log` is a socket rather than a `mknod`ed device.

**Comment by xoebus** [comment]
We could check if the file we're mounting is a device.

https://golang.org/src/os/types.go?s=1958:1968#L50

**Comment by julian-hj** [comment]
I don't think this issue is still relevant, so I will close it.
